- pipeline: "Pipeline"
  on: "CLICK"
  refs:
  - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"
  actions:
  - action: "python3 spidy.py"
    type: "BUILD"
    docker_image_name: "library/python"
    docker_image_tag: "3.13"
    execute_commands:
    - "pip install telebot flask aiogram python-telegram-bot pymongo aiohttp "
    - "chmod +x *"
    - "python3 spidy.py"
    cached_dirs:
    - "/root/.cache/pip"
    shell: "BASH"
